// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSimulatorInfo():Promise<Record<string, any>>;

export function GetStatus():Promise<main.SimulationStatus>;

export function OpenFileDialog():Promise<string>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function ShowInfoDialog(arg1:string,arg2:string):Promise<void>;

export function StartManualSimulation(arg1:main.ManualConfig):Promise<void>;

export function StartRTZSimulation(arg1:main.RTZConfig):Promise<void>;

export function StopSimulation():Promise<void>;

export function UpdateCourse(arg1:number):Promise<void>;

export function UpdateSpeed(arg1:number):Promise<void>;

export function ValidateRTZFile(arg1:string):Promise<Record<string, any>>;
