// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSimulatorInfo() {
  return window['go']['main']['App']['GetSimulatorInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowInfoDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowInfoDialog'](arg1, arg2);
}

export function StartManualSimulation(arg1) {
  return window['go']['main']['App']['StartManualSimulation'](arg1);
}

export function StartRTZSimulation(arg1) {
  return window['go']['main']['App']['StartRTZSimulation'](arg1);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}

export function UpdateCourse(arg1) {
  return window['go']['main']['App']['UpdateCourse'](arg1);
}

export function UpdateSpeed(arg1) {
  return window['go']['main']['App']['UpdateSpeed'](arg1);
}

export function ValidateRTZFile(arg1) {
  return window['go']['main']['App']['ValidateRTZFile'](arg1);
}
