 - name: Wails Build Action
  # You may pin to the exact commit or the version.
  # uses: dAppServer/wails-build-action@d0b7d7500f3344ebed78d1a59e3f183977d62d1f
  uses: dAppServer/wails-build-action@v2.2
  with:
    build-name: nmea-sim
    build-platform: windows/amd64,linux/amd64,darwin/arm64
    nsis: true
    package: true
          
