name: Simulator
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "windows/amd64", "darwin/universal"]
        include:
          - platform: "linux/amd64"
            os: ubuntu-latest
            name: nmea-sim
          - platform: "windows/amd64"
            os: windows-latest
            name: nmea-sim.exe
          - platform: "darwin/universal"
            os: macos-latest
            name: nmea-sim.dmg
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          wails-version: "v2.9.0"
          package: true
