name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Wails Build Action
        uses: dAppServer/wails-build-action@main
        with:
          build-name: nmea-sim
          build-platform: windows/amd64,linux/amd64,darwin/arm64
          wails-version: "v2.9.0"
          nsis: true
          package: true
